import { Color, cssVariablesString } from '@kematzy/zen-colors';
import { shareUrl } from './url.js';

/**
 * @param {object} opts
 * @param {string} opts.inputColor
 * @param {number} opts.weight
 * @param {string} opts.variableName
 * @param {'oklch' | 'hex' | 'rgb'} opts.format
 * @param {boolean} opts.includeThemeWrapper
 * @param {boolean} opts.clearDefaults
 * @param {boolean} opts.tailwindSteps
 * @param {string} [opts.share]
 */
export function exportThemeCss(opts) {
  const name = sanitizeVarName(opts.variableName) || 'primary';
  const base = new Color(opts.inputColor);
  const scale = base.scale(opts.weight, {
    preset: opts.tailwindSteps ? 'tailwind' : 'zen',
  });

  let vars = cssVariablesString(scale, name, { format: opts.format });
  // Indent body when wrapped in @theme
  if (opts.includeThemeWrapper || opts.clearDefaults) {
    vars = vars
      .trimEnd()
      .split('\n')
      .map((line) => (line ? `  ${line}` : line))
      .join('\n');
  } else {
    vars = vars.trimEnd();
  }

  const body = [];
  if (opts.clearDefaults) body.push('  --color-*: initial;', '');
  body.push(vars);

  const share = opts.share ?? shareUrl({ c: opts.inputColor, w: opts.weight, mode: 'scale' });
  const comment = `/* Generated by @kematzy/zen-colors · ${share} */`;

  if (opts.includeThemeWrapper) {
    return `@theme {\n${body.join('\n')}\n}\n\n${comment}\n`;
  }
  // Without @theme, clearDefaults still uses indented lines for the initial rule
  if (opts.clearDefaults) {
    return `${body.join('\n')}\n\n${comment}\n`;
  }
  return `${vars}\n\n${comment}\n`;
}

/**
 * @param {string} name
 */
export function sanitizeVarName(name) {
  return String(name || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '')
    .replace(/^-{1,}|-{1,}$/g, '');
}

/**
 * @param {string} name
 * @returns {string | null} error message
 */
export function validateVarName(name) {
  if (!name.trim()) return 'Name is required';
  if (!/^[a-z][a-z0-9-]*$/.test(name.trim())) {
    return 'Use lowercase letters, numbers, and hyphens; start with a letter';
  }
  return null;
}
