import { Color } from 'zen-colors';
import { shareUrl } from './url.js';

/**
 * @param {object} opts
 * @param {string} opts.inputColor
 * @param {number} opts.weight
 * @param {string} opts.variableName
 * @param {'oklch' | 'hex' | 'rgb'} opts.format
 * @param {boolean} opts.includeThemeWrapper
 * @param {boolean} opts.clearDefaults
 * @param {boolean} opts.tailwindSteps
 * @param {string} [opts.share]
 */
export function exportThemeCss(opts) {
  const name = sanitizeVarName(opts.variableName) || 'primary';
  const base = new Color(opts.inputColor);
  const lines = [];

  if (opts.tailwindSteps) {
    const scale = /** @type {Record<string, import('zen-colors').Color>} */ (
      base.scale(opts.weight, { preset: 'tailwind' })
    );
    const order = ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900', '950'];
    for (const step of order) {
      const color = scale[step];
      if (!color) continue;
      lines.push(`  --color-${name}-${step}: ${formatColor(color, opts.format)};`);
    }
  } else {
    const scale = /** @type {Record<string, import('zen-colors').Color>} */ (
      base.scale(opts.weight, { preset: 'zen' })
    );
    // Preserve insertion order from generateZenScale
    for (const [key, color] of Object.entries(scale)) {
      const suffix = key === 'base' ? 'base' : key;
      lines.push(`  --color-${name}-${suffix}: ${formatColor(color, opts.format)};`);
    }
  }

  const body = [];
  if (opts.clearDefaults) body.push('  --color-*: initial;', '');
  body.push(...lines);

  const share = opts.share ?? shareUrl({ c: opts.inputColor, w: opts.weight, mode: 'scale' });

  const comment = `/* Generated by zen-colors · ${share} */`;

  if (opts.includeThemeWrapper) {
    return `@theme {\n${body.join('\n')}\n}\n\n${comment}\n`;
  }
  return `${body.map((l) => l.replace(/^ {2}/, '')).join('\n')}\n\n${comment}\n`;
}

/**
 * @param {import('zen-colors').Color} color
 * @param {'oklch' | 'hex' | 'rgb'} format
 */
function formatColor(color, format) {
  if (format === 'hex') return color.hexString();
  if (format === 'rgb') return color.rgbString();
  return color.oklchString();
}

/**
 * @param {string} name
 */
export function sanitizeVarName(name) {
  return String(name || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '')
    .replace(/^-{1,}|-{1,}$/g, '');
}

/**
 * @param {string} name
 * @returns {string | null} error message
 */
export function validateVarName(name) {
  if (!name.trim()) return 'Name is required';
  if (!/^[a-z][a-z0-9-]*$/.test(name.trim())) {
    return 'Use lowercase letters, numbers, and hyphens; start with a letter';
  }
  return null;
}
